### ISSUE TITLE
Make score more prominent

### ISSUE THREAD

**Issue by cmavelis** [Aveli-games/flappy-fish#25]
- [x] Local score board
- [x] OPTIONAL: Global scoreboard via tiny webserver to hold the top 10

**Comment by avelitj12** [comment]
I was thinking about at least local score board, but I think a global scoreboard would be sick (would have to figure out how to post that, so if you're ok with that scope change, so we can learn)!

**Comment by avelitj12** [comment]
Assigning to myself to do the local scoreboard

**Comment by cmavelis** [comment]
https://docs.godotengine.org/en/stable/tutorials/networking/http_request_class.html#http-requests-in-godot
for the top 10

**Comment by cmavelis** [comment]
#27 starting the online scoreboard
